USE [SBBArchive]

INSERT INTO SBBArchive.dbo.UserGroups(Name) VALUES('Administrator')
INSERT INTO SBBArchive.dbo.UserGroups(Name) VALUES('Musikant')

INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('jakob', 'Jakob W. Larsen', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('kai', 'Kai Lindal', 'leif@odinsoftware.no', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('eva', 'Eva Bortne', 'leif@odinsoftware.no', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('torill', 'Torill Tynning', 'leif@odinsoftware.no', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('gunnar', 'Gunnar Hodne', 'leif@odinsoftware.no', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('leif', 'Leif Bjarte Johansson', 'leif@odinsoftware.no', 0, 1)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('stine', 'Stine Lillesund', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('sofia', 'Sofia Mahan', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('julia', 'Julia Cantillon', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('tone', 'Tone Lunde', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('ida', 'Ida Lykke Larsen', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('frank', 'Frank Roger Eikeland', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('astrid', 'Astrid Tynning', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('guro', 'Guro Elgheim Sivertsen', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('rune', 'Rune Vik', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('paniz', 'Paniz Golrang', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('eirik', 'Eirik Smith', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('per', 'Per Illguth', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('sindre', 'Sindre Skjøld', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('karianne', 'Karianne Nilsen', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('tor', 'Tor Asbjørn Hodnesdal Haga', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('ingvild', 'Ingvild Rosenberg', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('gaute', 'Gaute Jørpeland', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('øyvind', 'Øyvind Grong', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('brynjar', 'Brynjar Hammer', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('hanne', 'Hanne Kolstad', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('håkon', 'Håkon Skyberg', '', 0, 2)
INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive, UserGroupId) VALUES('lars', 'Lars Olav Laukvik', '', 0, 2)
--INSERT INTO SBBArchive.dbo.Users(UserName, Name, Email, Inactive) VALUES('', '', '', 0)